# Generated by Django 5.0.7 on 2025-02-27 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotion_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoPromotion',
        ),
    ]
