# Generated by Django 5.0.7 on 2025-02-27 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('promotion_app', '0002_delete_videopromotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('full_video_url', models.URLField(help_text='Paste Facebook, YouTube, or Google Drive video link')),
                ('youtube_video_id', models.CharField(max_length=100)),
                ('facebook_video_id', models.CharField(max_length=100)),
                ('google_drive_video_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
