# Generated by Django 5.0.7 on 2025-02-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion_app', '0004_alter_videopromotion_facebook_video_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopromotion',
            name='facebook_video_id',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='videopromotion',
            name='google_drive_video_id',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='videopromotion',
            name='youtube_video_id',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
